repositories:
  - name: jaegertracing
    url: https://jaegertracing.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: incubator
    url: https://charts.helm.sh/incubator

releases:
  - name: grafana
    chart: grafana/grafana
    needs:
      - prometheus
      - jaeger
      - tempo
    namespace: observability
    createNamespace: true
    installed: true
    missingFileHandler: Error
    values:
      - values/grafana.yaml

  - name: jaeger
    chart: jaegertracing/jaeger
    namespace: observability
    needs:
      - cassandra
    installed: false
    missingFileHandler: Error
    values:
      - values/jaeger.yaml

  - name: cassandra
    chart: incubator/cassandra
    namespace: observability
    createNamespace: true
    installed: true
    missingFileHandler: Error
    values:
      - values/cassandra.yaml

  - name: prometheus
    chart: prometheus-community/prometheus
    namespace: observability
    installed: true
    missingFileHandler: Error
    values:
      - values/prometheus.yaml

  - name: tempo
    chart: grafana/tempo-distributed
    namespace: observability
    installed: true
    missingFileHandler: Error
    values:
      - server:
          logLeveL: debug
      - metricsGenerator:
          enabled: true
          config:
            registry:
              collection_interval: 15s
              stale_duration: 15m
            processor:
              service_graphs:
                dimensions: []
              span_metrics:
                dimensions: []
            storage:
              remote_write:
                - url: http://prometheus-server.observability.svc.cluster.local:9090/api/v1/write
      - global_overrides:
          metrics_generator_processors:
            - service-graphs
            - span-metrics
      - traces:
          jaeger:
            grpc:
              enabled: true
            thriftCompact:
              enabled: true
              receiverConfig:
                endpoint: "0.0.0.0:6831"
            thriftBinary:
              enabled: true
              receiverConfig:
                endpoint: "0.0.0.0:6832"
            thriftHttp:
              enabled: true
              receiverConfig:
                endpoint: "0.0.0.0:14255"
      - search:
          enabled: true
