kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
      - hostPath: /Users/mattia/Repos/local-kubernetes-pvcs
        containerPath: /pvc
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        system-reserved: memory=2Gi
# - role: worker
#   kubeadmConfigPatches:
#   - |
#     kind: InitConfiguration
#     nodeRegistration:
#       kubeletExtraArgs:
#         system-reserved: memory=4Gi
# - role: worker
#   kubeadmConfigPatches:
#   - |
#     kind: InitConfiguration
#     nodeRegistration:
#       kubeletExtraArgs:
#         system-reserved: memory=4Gi
# - role: worker
#   kubeadmConfigPatches:
#   - |
#     kind: InitConfiguration
#     nodeRegistration:
#       kubeletExtraArgs:
#         system-reserved: memory=4Gi
# - role: worker
#   kubeadmConfigPatches:
#   - |
#     kind: InitConfiguration
#     nodeRegistration:
#       kubeletExtraArgs:
#         system-reserved: memory=4Gi
- role: worker
  extraMounts:
      - hostPath: /Users/mattia/Repos/local-kubernetes-pvcs
        containerPath: /pvc
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        system-reserved: memory=10Gi
- role: worker
  extraMounts:
      - hostPath: /Users/mattia/Repos/local-kubernetes-pvcs
        containerPath: /pvc
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        system-reserved: memory=10Gi
- role: worker
  extraMounts:
      - hostPath: /Users/mattia/Repos/local-kubernetes-pvcs
        containerPath: /pvc
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        system-reserved: memory=10Gi
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5001"]
    endpoint = ["http://kind-registry:5000"]
